/*
File: donator_flags.sqf
Author:

	Seathre

Description:

	Donator flag texture catalog.
	Format: [Display name, texture path, author]
__________________________________________________________*/

[
	['Blue','a3\data_f\flags\flag_blue_co.paa','Bohemia Interactive'],
	['Green','a3\data_f\flags\flag_green_co.paa','Bohemia Interactive'],
	['Red','a3\data_f\flags\flag_red_co.paa','Bohemia Interactive'],
	['White','a3\data_f\flags\flag_white_co.paa','Bohemia Interactive'],
	['Blue Firing Drill','a3\data_f\flags\flag_fd_blue_co.paa','Bohemia Interactive'],
	['Green Firing Drill','a3\data_f\flags\flag_fd_green_co.paa','Bohemia Interactive'],
	['Orange Firing Drill','a3\data_f\flags\flag_fd_orange_co.paa','Bohemia Interactive'],
	['Purple Firing Drill','a3\data_f\flags\flag_fd_purple_co.paa','Bohemia Interactive'],
	['Red Firing Drill','a3\data_f\flags\flag_fd_red_co.paa','Bohemia Interactive'],
	['White Damaged','a3\data_f\flags\flag_white_dmg_co.paa','Bohemia Interactive'],
	['Altis','a3\data_f\flags\flag_altis_co.paa','Bohemia Interactive'],
	['Altis Colonial','a3\data_f\flags\flag_altiscolonial_co.paa','Bohemia Interactive'],
	['Chernarus','a3\air_f\data\plane_flag_co.paa','Bohemia Interactive'],
	['Tanoa','a3\data_f_exp\flags\flag_tanoa_co.paa','Bohemia Interactive'],
	['United Kingdom','a3\data_f\flags\flag_uk_co.paa','Bohemia Interactive'],
	['United States','a3\data_f\flags\flag_us_co.paa','Bohemia Interactive'],
	['Livonia','a3\data_f_enoch\flags\flag_enoch_co.paa','Bohemia Interactive'],
	['Russia','a3\data_f_enoch\flags\flag_rus_co.paa','Bohemia Interactive'],
	['Netherlands','a3\missions_f_aow\data\img\flag_netherlands_co.paa','Bohemia Interactive'],
	['NATO','a3\data_f\flags\flag_nato_co.paa','Bohemia Interactive'],
	['AAF','a3\data_f\flags\flag_aaf_co.paa','Bohemia Interactive'],
	['CSAT','a3\data_f\flags\flag_csat_co.paa','Bohemia Interactive'],
	['FIA','a3\data_f\flags\flag_fia_co.paa','Bohemia Interactive'],
	['CTRG','a3\data_f_exp\flags\flag_ctrg_co.paa','Bohemia Interactive'],
	['Viper','a3\data_f_exp\flags\flag_viper_co.paa','Bohemia Interactive'],
	['Syndikat','a3\data_f_exp\flags\flag_synd_co.paa','Bohemia Interactive'],
	['IDAP','a3\data_f_orange\flags\flag_idap_co.paa','Bohemia Interactive'],
	['LDF','a3\data_f_enoch\flags\flag_eaf_co.paa','Bohemia Interactive'],
	['Looters','a3\data_f_enoch\flags\flag_looters_co.paa','Bohemia Interactive'],
	['ARMEX','a3\data_f\flags\flag_armex_co.paa','Bohemia Interactive'],
	['Bohemia Interactive','a3\data_f\flags\flag_bis_co.paa','Bohemia Interactive'],
	['ION Incorporated','a3\data_f\flags\flag_ion_co.paa','Bohemia Interactive'],
	['Larkin Aviation','a3\data_f\flags\flag_larkin_co.paa','Bohemia Interactive'],
	['Quontrol','a3\data_f\flags\flag_quontrol_co.paa','Bohemia Interactive'],
	['Vrana','a3\data_f\flags\flag_vrana_co.paa','Bohemia Interactive'],
	['United Nations','a3\data_f\flags\flag_uno_co.paa','Bohemia Interactive'],
	['Lars Blanken Gallery','a3\missions_f_aow\data\img\flag_blanken_co.paa','Bohemia Interactive'],
	['Belgium','a3\ui_f\data\map\markers\flags\belgium_ca.paa','Bohemia Interactive'],
	['Canada','a3\ui_f\data\map\markers\flags\canada_ca.paa','Bohemia Interactive'],
	['Catalonia','a3\ui_f\data\map\markers\flags\catalonia_ca.paa','Bohemia Interactive'],
	['Croatia','a3\ui_f\data\map\markers\flags\croatia_ca.paa','Bohemia Interactive'],
	['Czech Republic','a3\ui_f\data\map\markers\flags\czechrepublic_ca.paa','Bohemia Interactive'],
	['Denmark','a3\ui_f\data\map\markers\flags\denmark_ca.paa','Bohemia Interactive'],
	['EU','a3\ui_f\data\map\markers\flags\eu_ca.paa','Bohemia Interactive'],
	['France','a3\ui_f\data\map\markers\flags\france_ca.paa','Bohemia Interactive'],
	['Georgia','a3\ui_f\data\map\markers\flags\georgia_ca.paa','Bohemia Interactive'],
	['Germany','a3\ui_f\data\map\markers\flags\germany_ca.paa','Bohemia Interactive'],
	['Greece','a3\ui_f\data\map\markers\flags\greece_ca.paa','Bohemia Interactive'],
	['Hungary','a3\ui_f\data\map\markers\flags\hungary_ca.paa','Bohemia Interactive'],
	['Iceland','a3\ui_f\data\map\markers\flags\iceland_ca.paa','Bohemia Interactive'],
	['Italy','a3\ui_f\data\map\markers\flags\italy_ca.paa','Bohemia Interactive'],
	['Luxembourg','a3\ui_f\data\map\markers\flags\luxembourg_ca.paa','Bohemia Interactive'],
	['Norway','a3\ui_f\data\map\markers\flags\norway_ca.paa','Bohemia Interactive'],
	['Poland','a3\ui_f\data\map\markers\flags\poland_ca.paa','Bohemia Interactive'],
	['Portugal','a3\ui_f\data\map\markers\flags\portugal_ca.paa','Bohemia Interactive'],
	['Slovakia','a3\ui_f\data\map\markers\flags\slovakia_ca.paa','Bohemia Interactive'],
	['Slovenia','a3\ui_f\data\map\markers\flags\slovenia_ca.paa','Bohemia Interactive'],
	['Spain','a3\ui_f\data\map\markers\flags\spain_ca.paa','Bohemia Interactive'],
	['Syndicat','a3\ui_f\data\map\markers\flags\syndicat_ca.paa','Bohemia Interactive'],
	['Tanoa Gendarmerie','a3\ui_f\data\map\markers\flags\tanoagendarmerie_ca.paa','Bohemia Interactive'],
	['Red Crystal','a3\data_f\flags\flag_rcrystal_co.paa','Bohemia Interactive'],
	['Prisoners of War','a3\data_f\flags\flag_pow_co.paa','Bohemia Interactive'],
	['Race Flag','a3\signs_f\signspecial\data\checker_flag_co.paa','Bohemia Interactive'],
	['Australia','media\images\flags\flag_australia.jpg','Mission'],
	['Austria','media\images\flags\flag_austria.jpg','Mission'],
	['Austro-Hungarian Empire','media\images\flags\flag_austro_hungarian_empire.jpg','Mission'],
	['Austro-Hungarian Naval','media\images\flags\flag_austro_hungarian_naval.jpg','Mission'],
	['Canada (Coat of Arms)','media\images\flags\flag_canada_coa.jpg','Mission'],
	['East Germany','media\images\flags\flag_east_germany.jpg','Mission'],
	['Habsburg','media\images\flags\flag_habsburg.jpg','Mission'],
	['India','media\images\flags\flag_india.jpg','Mission'],
	['New Zealand','media\images\flags\flag_new_zealand.jpg','Mission'],
	['South Africa','media\images\flags\flag_south_africa.jpg','Mission'],
	['Gadsden','media\images\flags\flag_gadsden.jpg','Mission'],
	['Kekistani','media\images\flags\flag_kekistani.jpg','Mission'],
	['Lego','media\images\flags\flag_lego.jpg','Mission'],
	['Pride','media\images\flags\flag_pride.jpg','Mission'],
	['82nd','media\images\flags\82nd_AB.paa','Mission'],
	['Alaska','media\images\flags\flag_Alaska.jpg','Mission'],
	['Arkansas','media\images\flags\flag_Arkansas.jpg','Mission'],
	['Czech Republic','media\images\flags\flag_Czech_Republic.jpg','Mission'],
	['Egypt Army','media\images\flags\flag_Egypt_Army.jpg','Mission'],
	['Estonia (MoD)','media\images\flags\flag_Estonia_(MoD).jpg','Mission'],
	['Florida','media\images\flags\flag_Florida.jpg','Mission'],
	['Georgia State','media\images\flags\flag_Georgia_State.jpg','Mission'],
	['Gonzalez Texas Revolution','media\images\flags\flag_Gonzalez_Texas_Revolution.jpg','Mission'],
	['Iowa','media\images\flags\flag_Iowa.jpg','Mission'],
	['Join or Die','media\images\flags\flag_JoinOrDie.jpg','Mission'],
	['Lithuania (State)','media\images\flags\flag_Lithuania_(State).jpg','Mission'],
	['Louisiana','media\images\flags\flag_Louisiana.jpg','Mission'],
	['Mexico','media\images\flags\flag_Mexico.jpg','Mission'],
	['North Carolina','media\images\flags\flag_North_Carolina.jpg','Mission'],
	['North Dakota','media\images\flags\flag_North_Dakota.jpg','Mission'],
	['Poland (Coat of Arms)','media\images\flags\flag_Poland_(CoatOfArms).jpg','Mission'],
	['Russia (Imperial Standard)','media\images\flags\flag_Russia_(ImperialStandard).jpg','Mission'],
	['Russia','media\images\flags\flag_Russia.jpg','Mission'],
	['Scotland (Royal Banner)','media\images\flags\flag_Scotland_(RoyalBanner).jpg','Mission'],
	['Scotland','media\images\flags\flag_scotland.jpg','Mission'],
	['Slovakia','media\images\flags\flag_Slovakia.jpg','Mission'],
	['South Korea','media\images\flags\flag_South_Korea.jpg','Mission'],
	['Sweden','media\images\flags\flag_Sweden.jpg','Mission'],
	['Texas','media\images\flags\flag_Texas.jpg','Mission'],
	['Thailand','media\images\flags\flag_Thailand.jpg','Mission'],
	['Wales','media\images\flags\flag_Wales.jpg','Mission']
]
